config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'functionality', to: 'pages#functionality'
  get 'pricing', to: 'pages#pricing'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def about
  end
  
  def functionality
  end
  
  def pricing
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Your Website</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    
    <link href="app/assets/stylesheets/application.css" rel="stylesheet"> 
	  <link href="d//fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" 
          data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/"><i class="fa fa-spin fa-circle-o-notch" aria-hidden="true"></i> Home</a>
        </div>
    
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><%= link_to 'About', about_path %></li>
            <li><%= link_to 'Functionality', functionality_path %></li>
          </ul>
          
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Link</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" 
              aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Separated link</a></li>
              </ul>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
  	
    <%= yield %>
    
  </body>
</html>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>About Us</title>
	<%= javascript_include_tag 'about' %>
</head>

<body>
  
  <div>
    <section>
      <div id="heading1" class="container"> <h1 style="font-family: Montserrat">About Us</h1>
      </div>
      
      <div id="heading2" class="container"><h2>Welcome to the about us page<br/></h2>
      </div>
      
      <div id="about_paragraph" class="container">
        <p>yada yada yada</p>
      </div>
    </section>
  </div>
    
  </body>
</html>

app/views/pages/functionality.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Examples of Site Functionality</title>
	<%= javascript_include_tag 'functionality' %>
</head>

<body>

	<h3>Home Automation System Demo</h3>

    <div class="tabBar">
        <button id="showTemps" class="tabButton">Temperature</button>
        <button id="showLights" class="tabButton" current="current">Lights</button>
        <button id="showAlarms" class="tabButton">Alarms</button>
    </div>

    <form id="addADevice" method="post" action="temperature.html">
        <label>Add a device:</label>
        <input type="text" id="newDeviceID">
        <button>Add</button>
    </form>


    <div id="display">
    </div>

    <div>
        <h3>Link to pricing/checkout total demo page</h3>
        <%= link_to 'Pricing', pricing_path %>
    </div>
</body>


</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Home</title>
</head>

<body>
  
  <div>
    <section>
      <h1 style="font-family: Montserrat">Welcome to your website!</h1>
      <p>This is the home page</p>
    </section>
  </div>
    
</body>
</html>

app/views/pages/pricing.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Example of Pricing</title>
	<%= javascript_include_tag 'pricing' %>
</head>

<body>

	<h3>Total</h3>

    <div id="display">
    </div>
    
    <div id="success">
    </div>

</body>


</html>